# sudo cp deploy/logrotate.conf /etc/logrotate.d/odibrick
/var/log/odibrick/*.log {
    daily
    rotate 30
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    su odibrick odibrick
}
