-- ============================================================================
-- ODIBRICK MIGRATION 009: FINANCIAL OPERATIONS, RECONCILIATION & ACCOUNTING CONTROL
-- ============================================================================

CREATE TABLE IF NOT EXISTS financial_periods (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id         CHAR(26)        NOT NULL,
  period_code       VARCHAR(20)     NOT NULL, -- e.g. '2026-10', '2026-Q4'
  period_start      DATE            NOT NULL,
  period_end        DATE            NOT NULL,
  status            ENUM('OPEN','REVIEWING','CLOSED') NOT NULL DEFAULT 'OPEN',
  opened_by         BIGINT UNSIGNED NULL,
  reviewed_by       BIGINT UNSIGNED NULL,
  closed_by         BIGINT UNSIGNED NULL,
  opened_at         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at       DATETIME        NULL,
  closed_at         DATETIME        NULL,
  notes             VARCHAR(500)    NULL,
  summary_snapshot  JSON            NULL,
  created_at        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_fp_public_id (public_id),
  UNIQUE KEY uq_fp_period_code (period_code),
  KEY ix_fp_dates (period_start, period_end),
  KEY ix_fp_status (status),
  CONSTRAINT fk_fp_opened_by FOREIGN KEY (opened_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_fp_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_fp_closed_by FOREIGN KEY (closed_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS financial_reconciliation_runs (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id         CHAR(26)        NOT NULL,
  run_number        VARCHAR(32)     NOT NULL, -- e.g. 'ODB-RECON-2026-000001'
  period_start      DATE            NULL,
  period_end        DATE            NULL,
  status            ENUM('RUNNING','COMPLETED','COMPLETED_WITH_EXCEPTIONS','FAILED') NOT NULL DEFAULT 'RUNNING',
  operator_id       BIGINT UNSIGNED NOT NULL,
  records_scanned   INT UNSIGNED    NOT NULL DEFAULT 0,
  issues_found      INT UNSIGNED    NOT NULL DEFAULT 0,
  critical_issues   INT UNSIGNED    NOT NULL DEFAULT 0,
  warnings          INT UNSIGNED    NOT NULL DEFAULT 0,
  matched_records   INT UNSIGNED    NOT NULL DEFAULT 0,
  unmatched_records INT UNSIGNED    NOT NULL DEFAULT 0,
  summary_json      JSON            NULL,
  started_at        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at      DATETIME        NULL,
  created_at        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_frr_public_id (public_id),
  UNIQUE KEY uq_frr_run_number (run_number),
  KEY ix_frr_operator (operator_id),
  KEY ix_frr_status (status),
  CONSTRAINT fk_frr_operator FOREIGN KEY (operator_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS financial_exceptions (
  id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id             CHAR(26)        NOT NULL,
  exception_number      VARCHAR(32)     NOT NULL, -- e.g. 'ODB-EXC-2026-000001'
  fingerprint           VARCHAR(128)    NOT NULL,
  run_id                BIGINT UNSIGNED NULL,
  category              ENUM('PAYMENT','TRANSACTION','PAYOUT','INVOICE','REFUND',
                             'MAINTENANCE','DISPUTE','TENANCY','RECONCILIATION',
                             'DUPLICATE','DATA_INTEGRITY') NOT NULL,
  severity              ENUM('INFO','WARNING','CRITICAL') NOT NULL DEFAULT 'WARNING',
  status                ENUM('OPEN','ACKNOWLEDGED','INVESTIGATING','RESOLVED','IGNORED') NOT NULL DEFAULT 'OPEN',
  payment_id            BIGINT UNSIGNED NULL,
  payment_transaction_id BIGINT UNSIGNED NULL,
  payout_id             BIGINT UNSIGNED NULL,
  invoice_id            BIGINT UNSIGNED NULL,
  tenancy_id            BIGINT UNSIGNED NULL,
  property_id           BIGINT UNSIGNED NULL,
  dispute_id            BIGINT UNSIGNED NULL,
  title                 VARCHAR(255)    NOT NULL,
  description           TEXT            NOT NULL,
  expected_value        VARCHAR(255)    NULL,
  actual_value          VARCHAR(255)    NULL,
  assigned_to           BIGINT UNSIGNED NULL,
  resolution_notes      TEXT            NULL,
  resolved_by           BIGINT UNSIGNED NULL,
  resolved_at           DATETIME        NULL,
  created_at            DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_fe_public_id (public_id),
  UNIQUE KEY uq_fe_exception_number (exception_number),
  KEY ix_fe_fingerprint (fingerprint),
  KEY ix_fe_status (status),
  KEY ix_fe_category (category),
  KEY ix_fe_severity (severity),
  KEY ix_fe_run (run_id),
  KEY ix_fe_payment (payment_id),
  KEY ix_fe_payout (payout_id),
  KEY ix_fe_invoice (invoice_id),
  KEY ix_fe_tenancy (tenancy_id),
  CONSTRAINT fk_fe_run FOREIGN KEY (run_id) REFERENCES financial_reconciliation_runs (id) ON DELETE SET NULL,
  CONSTRAINT fk_fe_payment FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE SET NULL,
  CONSTRAINT fk_fe_payout FOREIGN KEY (payout_id) REFERENCES owner_payouts (id) ON DELETE SET NULL,
  CONSTRAINT fk_fe_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE SET NULL,
  CONSTRAINT fk_fe_tenancy FOREIGN KEY (tenancy_id) REFERENCES tenancies (id) ON DELETE SET NULL,
  CONSTRAINT fk_fe_assigned FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_fe_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
